#!/usr/bin/env node
// decisions/0007

import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const CHECK = process.argv.includes("--check");
const rel = (p) => relative(ROOT, p).split("\\").join("/");
const read = (p) => readFileSync(join(ROOT, p), "utf8");

/* ------------------------------------------------------------------ the map -- */

const MAP_FILES = ["src/page.js", "scripts/smoke.mjs"];
const BANNER = /^\s*(?:\/\*|\/\/)\s*[-=]{4,}\s*(.+?)\s*[-=]*\s*(?:\*\/)?\s*$/;
const BANNER_PAIR = /^\s*\/\*\s*----\s*(BEGIN|END): ([^-]+?)\s*-.*\*\/\s*$/;
const FN_DECL = /^(\s*)(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\s*\(/;
const FN_EXPR = /^(\s*)(?:var|const|let)\s+([A-Za-z_$][\w$]*)\s*=\s*(?:async\s+)?function\b/;
const CHECK_NAME = /^\s*check\("((?:[^"\\]|\\.)*)"/;

function mapFile(file) {
  const lines = read(file).split("\n");
  const sections = [];
  const fns = [];
  const checks = [];
  let before = null;
  lines.forEach((line, i) => {
    const n = i + 1;
    const pair = BANNER_PAIR.exec(line);
    if (pair) {
      if (pair[1] === "BEGIN") {
        before = sections.length ? sections[sections.length - 1].name.replace(/ \(continued\)$/, "") : null;
        sections.push({ line: n, name: `${pair[2].trim()} — stripped from the plugin build` });
      } else if (before) {
        sections.push({ line: n, name: `${before} (continued)` });
      }
      return;
    }
    const b = BANNER.exec(line);
    if (b && !/^\*\/?$/.test(b[1])) { sections.push({ line: n, name: b[1].replace(/\s*\*\/\s*$/, "") }); return; }
    const f = FN_DECL.exec(line) || FN_EXPR.exec(line);
    if (f) fns.push({ line: n, name: f[2], depth: Math.floor(f[1].length / 2) });
    const c = CHECK_NAME.exec(line);
    if (c) checks.push({ line: n, name: c[1] });
  });
  return { file, total: lines.length, sections, fns, checks };
}

function renderMap(maps) {
  const out = [];
  out.push("# Code map", "",
    "**Generated by `node scripts/code-map.mjs` — do not edit.** Section banners and function",
    "declarations of the files too large to read top to bottom, with line numbers. Open the",
    "range, not the file. Stale when `node scripts/code-map.mjs --check` fails.", "");
  for (const m of maps) {
    out.push(`## \`${m.file}\` — ${m.total} lines, ${m.sections.length} sections, ${m.fns.length} functions` +
             (m.checks.length ? `, ${m.checks.length} checks` : ""), "");
    out.push("### Sections", "", "| lines | section |", "|---|---|");
    m.sections.forEach((s, i) => {
      const end = i + 1 < m.sections.length ? m.sections[i + 1].line - 1 : m.total;
      out.push(`| ${s.line}–${end} | ${s.name} |`);
    });
    out.push("", "### Functions", "", "| line | function |", "|---|---|");
    for (const f of m.fns) out.push(`| ${f.line} | ${"· ".repeat(Math.max(0, f.depth - 1))}\`${f.name}\` |`);
    if (m.checks.length) {
      out.push("", "### Checks", "", "| line | check |", "|---|---|");
      for (const c of m.checks) out.push(`| ${c.line} | ${c.name} |`);
    }
    out.push("");
  }
  return out.join("\n");
}

/* ---------------------------------------------------------------- the index -- */

const CODE_DIRS = ["src", "plugin", "scripts"];
const CODE_EXT = new Set([".js", ".mjs", ".ts", ".css", ".html", ".ps1"]);
const SKIP = new Set(["scripts/shelf-snapshots"]);

function walk(dir, acc) {
  for (const name of readdirSync(dir).sort()) {
    const p = join(dir, name);
    const r = rel(p);
    if (SKIP.has(r) || name === "node_modules") continue;
    if (statSync(p).isDirectory()) { walk(p, acc); continue; }
    const ext = name.slice(name.lastIndexOf("."));
    if (CODE_EXT.has(ext)) acc.push(r);
  }
  return acc;
}

function buildIndex() {
  const codeFiles = CODE_DIRS.flatMap((d) => walk(join(ROOT, d), []));
  const proseFiles = walk(join(ROOT, ".ai-context"), []).concat(
    readdirSync(join(ROOT, ".ai-context")).sort().filter((f) => f.endsWith(".md")).map((f) => ".ai-context/" + f),
    ["decisions", "design"].flatMap((d) => readdirSync(join(ROOT, ".ai-context", d)).sort().map((f) => `.ai-context/${d}/${f}`)));
  const prose = [...new Set(proseFiles)].filter((f) => f.endsWith(".md") && !/code-(map|index)\.md$/.test(f));

  const issues = {};
  const records = {};
  const vsCalls = {};
  const add = (dict, key, file, line) => (dict[key] || (dict[key] = [])).push({ file, line });

  for (const file of codeFiles) {
    read(file).split("\n").forEach((line, i) => {
      for (const m of line.matchAll(/github#(\d+)/g)) add(issues, +m[1], file, i + 1);
      for (const m of line.matchAll(/\b(decisions|design)\/(\d{4})/g)) add(records, `${m[1]}/${m[2]}`, file, i + 1);
      if (file !== "src/page.js") {
        for (const m of line.matchAll(/__vs\.([A-Za-z_$][\w$]*)/g)) add(vsCalls, m[1], file, i + 1);
      }
    });
  }
  const proseIssues = {};
  for (const file of prose) {
    read(file).split("\n").forEach((line, i) => {
      for (const m of line.matchAll(/github#(\d+)/g)) add(proseIssues, +m[1], file, i + 1);
    });
  }

  const smoke = read("scripts/smoke.mjs").split("\n");
  const checkLines = {};
  smoke.forEach((line, i) => { const c = CHECK_NAME.exec(line); if (c) checkLines[c[1]] = i + 1; });
  const inv = read(".ai-context/invariants.md").split("\n");
  const invariants = [];
  let cur = null;
  inv.forEach((line, i) => {
    if (line.startsWith("## ")) { cur = { name: line.slice(3).trim(), line: i + 1, checks: new Set() }; invariants.push(cur); return; }
    if (!cur) return;
    for (const m of line.matchAll(/"([^"]{10,})"|(?<![*\w])\*([^*]{10,120})\*(?![*\w])/g)) {
      const q = (m[1] || m[2]).toLowerCase();
      for (const name of Object.keys(checkLines)) if (name.toLowerCase().includes(q)) cur.checks.add(name);
    }
  });

  return { issues, proseIssues, records, vsCalls, invariants, checkLines, codeFiles: codeFiles.length, prose: prose.length };
}

function renderIndex(ix) {
  const out = [];
  const sites = (arr) => arr.map((s) => `${s.file}:${s.line}`).join(", ");
  out.push("# Code index", "",
    "**Generated by `node scripts/code-map.mjs` — do not edit.** The inverted index over the",
    "markers already in the source: which code cites an issue, an ADR or a DDR; which check",
    "enforces each invariant; who calls each `__vs` entry point. Stale when",
    "`node scripts/code-map.mjs --check` fails.", "");
  const nums = [...new Set([...Object.keys(ix.issues), ...Object.keys(ix.proseIssues)].map(Number))].sort((a, b) => a - b);
  out.push(`## Issues — ${nums.length} cited (${Object.keys(ix.issues).length} in code, ${Object.keys(ix.proseIssues).length} in \`.ai-context/\`)`, "",
    "| issue | code sites | prose sites |", "|---|---|---|");
  for (const n of nums) {
    const c = ix.issues[n] || [], p = ix.proseIssues[n] || [];
    out.push(`| #${n} | ${c.length ? sites(c) : "—"} | ${p.length ? sites(p) : "—"} |`);
  }
  out.push("", `## Decision and design records cited in code — ${Object.keys(ix.records).length}`, "",
    "| record | code sites |", "|---|---|");
  for (const k of Object.keys(ix.records).sort()) out.push(`| \`${k}\` | ${sites(ix.records[k])} |`);
  out.push("", `## Invariants → checks — ${ix.invariants.length} sections in \`.ai-context/invariants.md\``, "",
    "| invariant (line) | check (smoke.mjs line) |", "|---|---|");
  for (const s of ix.invariants) {
    const cs = [...s.checks].map((c) => `${c} (${ix.checkLines[c]})`).join("; ");
    out.push(`| ${s.name} (${s.line}) | ${cs || "— no check named in the section"} |`);
  }
  const names = Object.keys(ix.vsCalls).sort();
  out.push("", `## \`__vs.*\` entry points → callers outside page.js — ${names.length}`, "",
    "| member | callers |", "|---|---|");
  for (const n of names) {
    const byFile = {};
    for (const s of ix.vsCalls[n]) byFile[s.file] = (byFile[s.file] || 0) + 1;
    out.push(`| \`__vs.${n}\` | ${Object.entries(byFile).map(([f, c]) => `${f} ×${c}`).join(", ")} |`);
  }
  out.push("");
  return out.join("\n");
}

/* ---------------------------------------------------------------------- run -- */

const outputs = [
  [".ai-context/code-map.md", renderMap(MAP_FILES.map(mapFile))],
  [".ai-context/code-index.md", renderIndex(buildIndex())],
];
let stale = 0;
for (const [file, text] of outputs) {
  let cur = null;
  try { cur = read(file); } catch { }
  if (CHECK) {
    if (cur !== text) { stale++; console.error(`code-map: ${file} is stale -- run: node scripts/code-map.mjs`); }
  } else {
    writeFileSync(join(ROOT, file), text, "utf8");
    console.log(`code-map: wrote ${file} (${text.split("\n").length} lines)`);
  }
}
if (CHECK) {
  if (stale) process.exit(1);
  console.log("code-map: both generated files are current");
}
